name: Build RayLauncher

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows-msvc:
    name: Windows MSVC (x64)
    runs-on: windows-2022

    env:
      INSTALL_DIR: install
      INSTALL_PORTABLE_DIR: install-portable
      BUILD_DIR: build
      BUILD_TYPE: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short version
        shell: bash
        run: |
          ver_short=`git rev-parse --short HEAD`
          echo "VERSION=$ver_short" >> $GITHUB_ENV

      - name: Install Qt 6
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: "==3.1.*"
          py7zrversion: ">=0.20.2"
          version: "6.8.1"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2022_64"
          modules: "qt5compat qtimageformats qtnetworkauth"
          cache: true

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2022
          arch: amd64

      - name: Install NSIS NScurl plugin
        shell: pwsh
        run: |
          New-Item -Name NSISPlugins -ItemType Directory -Force | Out-Null
          Invoke-WebRequest https://github.com/negrutiu/nsis-nscurl/releases/download/v24.9.26.122/NScurl.zip -OutFile NSISPlugins\NScurl.zip
          Expand-Archive -Path NSISPlugins\NScurl.zip -DestinationPath NSISPlugins\NScurl

      - name: Configure CMake
        shell: pwsh
        run: |
          cmake -S . -B ${{ env.BUILD_DIR }} `
            -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} `
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} `
            -DENABLE_LTO=ON `
            -DLauncher_ENABLE_JAVA_DOWNLOADER=ON `
            -DLauncher_BUILD_PLATFORM=official `
            -DLauncher_QT_VERSION_MAJOR=6 `
            -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreadedDLL" `
            -DLauncher_FORCE_BUNDLED_LIBS=ON `
            -DLauncher_BUILD_ARTIFACT=Windows-MSVC-Qt6 `
            -G Ninja

      - name: Build
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}

      - name: Run tests
        continue-on-error: true
        run: ctest -E "^example64|example$" --test-dir ${{ env.BUILD_DIR }} --output-on-failure -C ${{ env.BUILD_TYPE }}

      - name: Install
        run: cmake --install ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}

      - name: Generate install manifest
        shell: pwsh
        run: |
          Get-ChildItem ${{ env.INSTALL_DIR }} -Recurse -File |
            ForEach-Object FullName |
            Resolve-Path -Relative |
            ForEach-Object { $_.TrimStart('.\').Replace('install\', '') } |
            Out-File -FilePath ${{ env.INSTALL_DIR }}/manifest.txt

      - name: Build portable bundle
        shell: pwsh
        run: |
          Copy-Item -Path ${{ env.INSTALL_DIR }} -Destination ${{ env.INSTALL_PORTABLE_DIR }} -Recurse
          cmake --install ${{ env.BUILD_DIR }} --prefix ${{ env.INSTALL_PORTABLE_DIR }} --component portable

      - name: Build installer
        shell: pwsh
        run: |
          cd ${{ env.INSTALL_DIR }}
          makensis -NOCD "${{ github.workspace }}/${{ env.BUILD_DIR }}/program_info/win_install.nsi"

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: RayLauncher-Setup-${{ env.VERSION }}
          path: RayLauncher-Setup.exe

      - name: Upload portable
        uses: actions/upload-artifact@v4
        with:
          name: RayLauncher-Portable-${{ env.VERSION }}
          path: ${{ env.INSTALL_PORTABLE_DIR }}/**
